"""Initial migration

Revision ID: 951f9b058129
Revises: 
Create Date: 2023-11-01 10:54:04.962602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951f9b058129'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publishers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('id_publisher', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_publisher'], ['publishers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_book', sa.Integer(), nullable=False),
    sa.Column('id_shop', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_book'], ['books.id'], ),
    sa.ForeignKeyConstraint(['id_shop'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('date_sale', sa.DateTime(), nullable=False),
    sa.Column('id_stock', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_stock'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    op.drop_table('stocks')
    op.drop_table('books')
    op.drop_table('shops')
    op.drop_table('publishers')
    # ### end Alembic commands ###
