FROM python:3.10.12

WORKDIR /app

COPY . /app

RUN pip install -r requirements.txt && pip install fastapi uvicorn

EXPOSE 80

CMD ["uvicorn", "response_endpoint:app", "--host", "0.0.0.0", "--port", "80"]